### ISSUE TITLE
error 105

### ISSUE THREAD

**Issue by Shakeel1679** [knowmics-lab/oncoreport#31] opened 2024-03-15 13:09 UTC
while installing oncoreport  the part for cosmic download
i use the usename the email address for my account cosmic and password
i get unknown error code 105

**Comment by Shakeel1679** [comment] 2024-03-15 14:19
Hence cannot download.how to solve this problem?hence cannot download the software

**Comment by alaimos** [comment] 2024-03-16 07:43
Thank you for your report. We are already aware of the issue caused by changes in the cosmic databases dump structure. We are planning to release a new version next week that should solve this problem and introduce other important changes.

**Comment by Shakeel1679** [comment] 2024-03-16 09:20
Thanks

**Comment by alaimos** [comment] 2024-03-22 09:09
I'm closing this bug since we published the next release.
If you encounter any new problems, please open a new issue.

**Closed by alaimos** 2024-03-22 09:09 UTC
Labels: bug
